// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GiveDataInsightsRequest {
    #[prost(string, tag="1")]
    pub data_source_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GiveDataInsightsResponse {
    #[prost(string, tag="1")]
    pub resp_message: ::prost::alloc::string::String,
}
include!("data_processor.v1.tonic.rs");
// @@protoc_insertion_point(module)