spring:
  cloud:
    gateway:
      server:
        webflux:
          filter:
            json-to-grpc:
              enabled: false
  application:
    name: gateway
  profiles:
    active: dev
server:
  port: 9000
jwt:
  secret: 1A50EF4F7AB1F6069BC04EEABFA52D66257D47E7FBBE0D7C1C20D2D88E9489C5
  issuer: https://nexussphere.com

#   Configure cors for all the services/ Global cors configuration.
#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          global-cors:
#            cors-configurations:
#              '[/**]':
#                allowed-origins: 'http://localhost:3000'
#                allowed-methods:
#                  - GET
#                  - POST
#                  - PUT
#                  - DELETE
#                  - PATCH
#                allow-credentials: true
#                allowed-headers:
#                  - "*"
#            add-to-simple-url-handler-mapping: true