services:
  # This proxy only need when running the application using docker-compose.
  web:
    container_name: nexus-web
    image: biswasakash/nexussphere-web:docker
    ports:
      - "3001:3000"
    networks:
      - service-network

  # Authentication gateway for the services.
  gateway:
    container_name: nexus-gateway
    image: biswasakash/nexussphere-gateway:local
    networks:
      - service-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - core

  core:
    container_name: nexus-core
    image: biswasakash/nexussphere-core:local
    networks:
      - service-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres

  postgres:
    container_name: nexus-postgres
    image: postgres:18.3-bookworm
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres-network

  mongo:
    container_name: nexus-mongo
    image: mongo:8.0-noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - mongo-network

networks:
  proxy-network:
    driver: bridge
  service-network:
    driver: bridge
  mongo-network:
    driver: bridge
  postgres-network:
    driver: bridge
