# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_processor/v1/data_information_service.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'data_processor/v1/data_information_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0data_processor/v1/data_information_service.proto\x12\x11\x64\x61ta_processor.v1\"?\n\x17GiveDataInsightsRequest\x12$\n\x0e\x64\x61ta_source_id\x18\x01 \x01(\tR\x0c\x64\x61taSourceId\"=\n\x18GiveDataInsightsResponse\x12!\n\x0cresp_message\x18\x01 \x01(\tR\x0brespMessage2\x83\x01\n\x14\x44\x61taProcessorService\x12k\n\x10GiveDataInsights\x12*.data_processor.v1.GiveDataInsightsRequest\x1a+.data_processor.v1.GiveDataInsightsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_processor.v1.data_information_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GIVEDATAINSIGHTSREQUEST']._serialized_start=71
  _globals['_GIVEDATAINSIGHTSREQUEST']._serialized_end=134
  _globals['_GIVEDATAINSIGHTSRESPONSE']._serialized_start=136
  _globals['_GIVEDATAINSIGHTSRESPONSE']._serialized_end=197
  _globals['_DATAPROCESSORSERVICE']._serialized_start=200
  _globals['_DATAPROCESSORSERVICE']._serialized_end=331
# @@protoc_insertion_point(module_scope)
