# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from data_processor.v1 import data_information_service_pb2 as data__processor_dot_v1_dot_data__information__service__pb2


class DataProcessorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GiveDataInsights = channel.unary_unary(
                '/data_processor.v1.DataProcessorService/GiveDataInsights',
                request_serializer=data__processor_dot_v1_dot_data__information__service__pb2.GiveDataInsightsRequest.SerializeToString,
                response_deserializer=data__processor_dot_v1_dot_data__information__service__pb2.GiveDataInsightsResponse.FromString,
                _registered_method=True)


class DataProcessorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GiveDataInsights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GiveDataInsights': grpc.unary_unary_rpc_method_handler(
                    servicer.GiveDataInsights,
                    request_deserializer=data__processor_dot_v1_dot_data__information__service__pb2.GiveDataInsightsRequest.FromString,
                    response_serializer=data__processor_dot_v1_dot_data__information__service__pb2.GiveDataInsightsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data_processor.v1.DataProcessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data_processor.v1.DataProcessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataProcessorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GiveDataInsights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/data_processor.v1.DataProcessorService/GiveDataInsights',
            data__processor_dot_v1_dot_data__information__service__pb2.GiveDataInsightsRequest.SerializeToString,
            data__processor_dot_v1_dot_data__information__service__pb2.GiveDataInsightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
