# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc



class StatisticalServiceStub:
    """The statistical tools that mostly use for know the insights of the data.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """


class StatisticalServiceServicer:
    """The statistical tools that mostly use for know the insights of the data.
    """


def add_StatisticalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data_processor.v1.StatisticalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('data_processor.v1.StatisticalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatisticalService:
    """The statistical tools that mostly use for know the insights of the data.
    """
